# Environment configuration
env:
  name: "test_env"
  max_steps: 100
  timeout_seconds: 300

# Agent configuration  
agent:
  name: "test_agent"
  max_retries: 3
  memory_size: 10
  temperature: 0.7

# LLM configuration
llm:
  model: "gpt-4o-mini" 
  max_tokens: 16000
  temperature: 0.7
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0
  timeout_seconds: 30

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/agent.log"
  max_file_size_mb: 10
  backup_count: 5
  console_output: true
